### PR TITLE
Trav

### LINKED ISSUE #3: Only has Functor instance only.
The problem is *only* described at https://github.com/lpsmith/postgresql-simple/issues/270.

### PR DESCRIPTION
**Pull request by phadej**
Improves upon #2 and fixes #3

### CODE REVIEW

**Comment by phadej** [comment]
Seems that travis is not enabled.

**Comment by hvr** [comment]
@phadej we need to review all revdeps of `Only` that reexport `Only` for their upper bounds;

A quick query tells me that

- heterogeneous-list-literals
- indexed-list-literals
- optparse-generic

reexport the `Only` type but don't have `Only < 0.1.1` upper bound in place.

- cassava, postgresql-simple, sqlite-simple have a proper upper bound in place
- roc-id appears to use `Only` only internally w/o reexporting it

PS: I've enabled Travis now

**Comment by phadej** [comment]
@hvr one option is to have major bump and mention why it so in the changelog; for me it's fine, i'd need to bump bounds/make a release either way.

**Comment by hvr** [comment]
@phadej well, that kind of oversignalling would be in vain if the respective maintainers aren't aware of the issue and then merely start depending on `Only >= 0.1 && < 0.3` ending up with unsound API versioning. I'll try to reach out to the respective maintainers.

**Comment by phadej** [comment]
ping?

**Comment by phadej** [comment]
Have the maintainers of `Only` reverse dependencies responded anything?

**Comment by phadej** [comment]
I guess this is not going to happen.

**Comment by andreasabel** [comment]
> A quick query tells me that
> 
>     * heterogeneous-list-literals
> 
>     * indexed-list-literals
> 
>     * optparse-generic
> 
> 
> reexport the `Only` type but don't have `Only < 0.1.1` upper bound in place.

They could simply be revised.

**Pull request closed without merging**
